name: Customer Service
server:
  port: 8181
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: demo
    password: shubham
    driverClassName: oracle.jdbc.driver.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.Oracle9Dialect
    hibernate.ddl-auto: create
    show-sql: true
